### PR TITLE
Inference para

### PR DESCRIPTION
**Pull request by hyanwong**
As discussed in Slack.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Merged, will sync up with overleaf in a few hours (out for a meeting ATM)

**Comment by jeromekelleher** [comment]
This is great, loads of helpful detail!

**Comment by hyanwong** [comment]
Thanks. I have a few extra things to add in, will make a (very minor) follow-up PR.

**Comment by jeromekelleher** [comment]
I just synced with Overleaf and fixed some latex issues, so feel free  to work away on overleaf for the follow-ups if that's easier.

**Comment by hyanwong** [comment]
Great, thanks. Shall I change-track to this section?

**Pull request merged**
