### PR TITLE
Convert function for KwARG output

### PR DESCRIPTION
**Pull request by a-ignatieva**
#133 Not thoroughly tested yet! Seems to work on the kreitman example (which I've added to the examples folder). 
kreitman_kwarg

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM - I say we merge! @hyanwong, any thoughts?

**Comment by jeromekelleher** [comment]
The graph looks great I think, you can really see the structure that's being inferred. Looks quite similar to what's in one of Yun's papers as well I think, doesn't it?

**Comment by hyanwong** [comment]
Yes, this looks really nice to me. I think we should merge and we can always make improvements after.

**Comment by hyanwong** [comment]
By the way, this is what happens when you run keep_unary_in_coal on the KwARG output. I'm assuming that we don't want to do that, though.

Screenshot 2022-03-10 at 18 09 13

**Pull request merged**
