### PR TITLE
Use pydot rather than pygraphviz, to produce deterministic results

### LINKED ISSUE #75: Graph viz layout seemingly non-deterministic
Weirdly, when I run the following code after restarting the notebook kernel, I get slightly different X layouts. This is *really* annoying. It seems like the dot layout engine should be deterministic, so I don't know what's going on here.

```
ts = argutils.sim_coalescent(4, 0.001, 1000, seed=123)
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1) = plt.subplots(1, 1, figsize=(10,10))
argutils.viz.draw(ts, ax1, use_ranked_times=True)
```

1st attempt
image

repeat attempt
image

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #75 for me, although I'm not entirely sure why!

### CODE REVIEW

**Comment by hyanwong** [comment]
@jeromekelleher : does the following code in a Jupiter notebook produce the same layout for you as shown in the plot below?

```
import argutils
import matplotlib.pyplot as plt
import string

ts = argutils.sim_coalescent(4, 0.001, 1000, seed=123)
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20,10))
pos = argutils.viz.draw(ts, ax1, use_ranked_times=True, tweak_x={24: 15, 23: 5, 22: 10, 21: 10})
new_ts, node_map = ts.simplify(map_nodes=True)
_ = argutils.viz.draw(new_ts, ax2, pos={node_map[i]:p  for i, p in pos.items()})
```

image

**Comment by hyanwong** [comment]
P.s. I think this is actually quite a good example to use for the paper: what do you think?

**Comment by hyanwong** [comment]
In particular, we have 2 diamonds (one of which actually looks like a diamond!), simplify produces 2 roots, there's some trapped material (I think), and the full simplification actually produces an edge from A to O that should go though N, but is not shown like that because N is not a coalescent node in that part of the genome. Here are the trees:

```
Original
3.18┊    24    ┊    24    ┊    24    ┊    24    ┊    24    ┊    24    ┊    24    ┊  
    ┊   ┏━┻━━┓ ┊   ┏━┻━━┓ ┊   ┏━┻━━┓ ┊   ┏━┻━━┓ ┊     ┃    ┊     ┃    ┊     ┃    ┊  
2.99┊   ┃   23 ┊   ┃   23 ┊   ┃   23 ┊   ┃   23 ┊     ┃    ┊    23    ┊    23    ┊  
    ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊     ┃    ┊     ┃    ┊     ┃    ┊  
2.92┊  21    ┃ ┊  21    ┃ ┊  21    ┃ ┊  21    ┃ ┊    21    ┊    22    ┊    22    ┊  
    ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊     ┃    ┊     ┃    ┊     ┃    ┊  
2.52┊  20    ┃ ┊  20    ┃ ┊  20    ┃ ┊  20    ┃ ┊    20    ┊    20    ┊    20    ┊  
    ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊     ┃    ┊     ┃    ┊     ┃    ┊  
2.14┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊  19    ┃ ┊    19    ┊    19    ┊    19    ┊  
    ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┏━┻━━┓ ┊   ┏━┻━━┓ ┊   ┏━┻━━┓ ┊  
2.07┊  17    ┃ ┊  17    ┃ ┊  17    ┃ ┊  18    ┃ ┊  18    ┃ ┊  18    ┃ ┊  18    ┃ ┊  
    ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊  
1.74┊   ┃   15 ┊   ┃   15 ┊   ┃   15 ┊   ┃   15 ┊   ┃   16 ┊   ┃   16 ┊   ┃   16 ┊  
    ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊   ┃    ┃ ┊  
0.83┊  14    ┃ ┊  14    ┃ ┊  14    ┃ ┊  14    ┃ ┊  14    ┃ ┊  14    ┃ ┊  14    ┃ ┊  
    ┊   ┃    ┃ ┊ ┏━┻━┓  ┃ ┊ ┏━┻━┓  ┃ ┊ ┏━┻━┓  ┃ ┊ ┏━┻━┓  ┃ ┊ ┏━┻━┓  ┃ ┊ ┏━┻━┓  ┃ ┊  
0.55┊  13    ┃ ┊ 13  ┃  ┃ ┊ 13  ┃  ┃ ┊ 13  ┃  ┃ ┊ 13  ┃  ┃ ┊ 13  ┃  ┃ ┊ 13  ┃  ┃ ┊  
    ┊ ┏━┻━┓  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊  
0.52┊ ┃  11  ┃ ┊ ┃  12  ┃ ┊ ┃  12  ┃ ┊ ┃  12  ┃ ┊ ┃  12  ┃ ┊ ┃  12  ┃ ┊ ┃  12  ┃ ┊  
    ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊  
0.52┊ 10  ┃  ┃ ┊ 10  ┃  ┃ ┊ 10  ┃  ┃ ┊ 10  ┃  ┃ ┊ 10  ┃  ┃ ┊ 10  ┃  ┃ ┊ 10  ┃  ┃ ┊  
    ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊  
0.50┊ 8   ┃  ┃ ┊ 8   ┃  ┃ ┊ 8   ┃  ┃ ┊ 8   ┃  ┃ ┊ 8   ┃  ┃ ┊ 8   ┃  ┃ ┊ 9   ┃  ┃ ┊  
    ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊  
0.23┊ ┃   ┃  7 ┊ ┃   ┃  7 ┊ ┃   ┃  7 ┊ ┃   ┃  7 ┊ ┃   ┃  7 ┊ ┃   ┃  7 ┊ ┃   ┃  7 ┊  
    ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊ ┃   ┃  ┃ ┊  
0.22┊ ┃   6  ┃ ┊ ┃   6  ┃ ┊ ┃   6  ┃ ┊ ┃   6  ┃ ┊ ┃   6  ┃ ┊ ┃   6  ┃ ┊ ┃   6  ┃ ┊  
    ┊ ┃  ┏┻┓ ┃ ┊ ┃  ┏┻┓ ┃ ┊ ┃  ┏┻┓ ┃ ┊ ┃  ┏┻┓ ┃ ┊ ┃  ┏┻┓ ┃ ┊ ┃  ┏┻┓ ┃ ┊ ┃  ┏┻┓ ┃ ┊  
0.01┊ ┃  ┃ ┃ 4 ┊ ┃  ┃ ┃ 4 ┊ ┃  ┃ ┃ 5 ┊ ┃  ┃ ┃ 5 ┊ ┃  ┃ ┃ 5 ┊ ┃  ┃ ┃ 5 ┊ ┃  ┃ ┃ 5 ┊  
    ┊ ┃  ┃ ┃ ┃ ┊ ┃  ┃ ┃ ┃ ┊ ┃  ┃ ┃ ┃ ┊ ┃  ┃ ┃ ┃ ┊ ┃  ┃ ┃ ┃ ┊ ┃  ┃ ┃ ┃ ┊ ┃  ┃ ┃ ┃ ┊  
0.00┊ 0  2 3 1 ┊ 0  2 3 1 ┊ 0  2 3 1 ┊ 0  2 3 1 ┊ 0  2 3 1 ┊ 0  2 3 1 ┊ 0  2 3 1 ┊  
    0         45         111        579        821        868        928       1000 
```

Simplified:
```
3.18┊     8   ┊     8   ┊         ┊  
    ┊   ┏━┻━┓ ┊   ┏━┻━┓ ┊         ┊  
2.14┊   ┃   ┃ ┊   ┃   ┃ ┊     7   ┊  
    ┊   ┃   ┃ ┊   ┃   ┃ ┊   ┏━┻━┓ ┊  
0.83┊   ┃   ┃ ┊   6   ┃ ┊   6   ┃ ┊  
    ┊   ┃   ┃ ┊ ┏━┻┓  ┃ ┊ ┏━┻┓  ┃ ┊  
0.55┊   5   ┃ ┊ ┃  ┃  ┃ ┊ ┃  ┃  ┃ ┊  
    ┊ ┏━┻┓  ┃ ┊ ┃  ┃  ┃ ┊ ┃  ┃  ┃ ┊  
0.22┊ ┃  4  ┃ ┊ ┃  4  ┃ ┊ ┃  4  ┃ ┊  
    ┊ ┃ ┏┻┓ ┃ ┊ ┃ ┏┻┓ ┃ ┊ ┃ ┏┻┓ ┃ ┊  
0.00┊ 0 2 3 1 ┊ 0 2 3 1 ┊ 0 2 3 1 ┊  
    0        45        821      1000 
```

**Comment by jeromekelleher** [comment]
LGTM, let's merge it and give it a go

**Comment by jeromekelleher** [comment]
It's a nice example all right!

**Comment by hyanwong** [comment]
That's the same example, actually (I switched the X axis back to how we had it before, as it seemed to work better in this case). Sorry for the confusion

**Comment by hyanwong** [comment]
Here's the code with how it works now (note the negative numbers when tweaking the X points):

```
import argutils
import matplotlib.pyplot as plt

ts = argutils.viz.label_nodes(argutils.sim_coalescent(4, 0.001, 1000, seed=123))
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20,10))
pos = argutils.viz.draw(ts, ax1, use_ranked_times=True, tweak_x={24: -15, 23: -5, 22: -10, 21: -10})
new_ts, node_map = ts.simplify(map_nodes=True)
_ = argutils.viz.draw(new_ts, ax2, pos={node_map[i]:p  for i, p in pos.items()})
```

And the plot on my machine looks like this, which I suspect is what you will get too:

image

**Comment by jeromekelleher** [comment]
Ah, now it looks the same.

Just spent the last hour fiddling with igraph to see if we could get better layouts. It's not very good, I think, so your solution is as good as it's going to get.

**Comment by hyanwong** [comment]
Sorry if that sent you down a blind alley. Probably worth investigating the various packages though. At least pydot gives us a viable solution.

**Pull request merged**
