### PR TITLE
add numpy to ancestry

### PR DESCRIPTION
**Pull request by awohns**
need to import numpy for @hyanwong's `simplify_keeping_unary_in_coal` in argutils/ancestry.py to work

### CODE REVIEW

**Comment by hyanwong** [comment]
Good spot, sorry

**Comment by jeromekelleher** [comment]
Knew we should have added tests for this - can you add simple tests for any new functions like this that to into ancestry.py please?

**Comment by hyanwong** [comment]
Do we automatically run argutils/test.py on PR submission ATM?

**Comment by jeromekelleher** [comment]
> I guess you mean argutils/test.py? Do we automatically run that on PR submission ATM?

Yes, and no. There's no need to setup automatic CI here I think, but good to keep the code working, at least the semi complicated stuff.

**Pull request merged**
